// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXtahK3ho6v92RZAsZINwaLCTZnYorvrU',
    appId: '1:1078903728805:android:87302f3b5ee8949d303b4c',
    messagingSenderId: '1078903728805',
    projectId: 'task-495621',
    storageBucket: 'task-495621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM0VT2ZNqdBwRo_eLo_LnI4J8A22Pzr_Q',
    appId: '1:1078903728805:ios:6cc7a07fe1ce0464303b4c',
    messagingSenderId: '1078903728805',
    projectId: 'task-495621',
    storageBucket: 'task-495621.firebasestorage.app',
    androidClientId: '1078903728805-cejeh5rv7jq3ocupvtb2gbj4p22pva92.apps.googleusercontent.com',
    iosClientId: '1078903728805-9dkrdlngd4huh1i0qidescrgakh2kpda.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasksManagementApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRr6I2OoIOf8rECtKqtAygj8hJUb_EXhA',
    appId: '1:1078903728805:web:46eee165326da5b0303b4c',
    messagingSenderId: '1078903728805',
    projectId: 'task-495621',
    authDomain: 'task-495621.firebaseapp.com',
    storageBucket: 'task-495621.firebasestorage.app',
    measurementId: 'G-FF7R4HKF2R',
  );

}